apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: product-system
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http