"""initial

Revision ID: 9df12bd7e139
Revises: 
Create Date: 2025-06-03 22:00:46.157391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df12bd7e139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_categoria'])

    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint('movimiento_inventario_producto_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'producto', ['producto_id'], ['id'])

    with op.batch_alter_table('orden_compra_item', schema=None) as batch_op:
        batch_op.drop_constraint('orden_compra_item_orden_compra_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orden_compra', ['orden_compra_id'], ['id'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('precio_costo',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.alter_column('precio_venta',
               existing_type=sa.NUMERIC(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('precio_venta',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('precio_costo',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('orden_compra_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orden_compra_item_orden_compra_id_fkey', 'orden_compra', ['orden_compra_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movimiento_inventario_producto_id_fkey', 'producto', ['producto_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
